warm_contentful_entry_cache:
  cron: "0 3 * * *"
  class: "WarmEntryCacheJob"
  description: This is a content driven service and the content is sourced by
    the Contentful API. As a single point of failure we have a Redis cache to
    provide some resilience to downtime or minor connection issues. As this
    service is used infrequently by real users, we automatically update the
    cache.

delete_stale_journeys:
  cron: "0 2 * * *"
  class: "DeleteStaleJourneysJob"
  description: Automatically remove Journey and associated child records when
    we identify it as having become stale. This is intended to free up unused
    database rows given every new specification generates 100-200 rows.
